### ISSUE TITLE
DOMDocument::createElement(): unterminated entity reference error

### ISSUE THREAD

**Issue by Brah0um** [skolodyazhnyy/symfony-rpc-bundle#17]
Hi,

I am seeing the following error when a string has a & in it:

my string : "PAO & DAO - Publication et Dessin Assisté par Ordinateur"

```sh
Warning: DOMDocument::createElement(): unterminated entity reference  DAO - Publication et Dessin Assisté par Ordinateur in /var/www/vendor/seven/symfony-rpc-bundle/Seven/RpcBundle/XmlRpc/ValueType/StringType.php line 24
```

There seems to be a reference to avoiding these types of errors:
http://www.php.net/manual/en/domdocument.createelement.php#73617 if it helps.

If I can I'll make a fix !

Thanks,

**Comment by burahimu** [comment]
See #18
